import type { Coords, DayHours, ImagingCenter } from "./types";

const WEEKDAYS = (open: number, close: number): Record<string, DayHours> => ({
  mon: { open, close },
  tue: { open, close },
  wed: { open, close },
  thu: { open, close },
  fri: { open, close },
});

/**
 * 12 seeded NYC-metro imaging centers with deliberately diverse profiles
 * so ranking weight changes produce visibly different orderings.
 */
export const CENTERS: ImagingCenter[] = [
  {
    id: "midtown-imaging",
    name: "Midtown Imaging Group",
    address: {
      line1: "485 Madison Ave, 6th Fl",
      city: "New York",
      state: "NY",
      zip: "10022",
    },
    coords: { lat: 40.7589, lng: -73.9745 },
    phone: "(212) 555-0142",
    hours: "Mon–Fri 7am–9pm, Sat 8am–4pm",
    weeklyHours: { ...WEEKDAYS(7, 21), sat: { open: 8, close: 16 } },
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography", "DEXA"],
    subspecialties: ["Neuro", "MSK", "Body"],
    accreditations: ["ACR-MRI", "ACR-CT", "ACR-Mammography", "ACR-Ultrasound"],
    patientRating: 4.7,
    reviewCount: 412,
    avgTurnaroundHours: 18,
    nextAvailableHours: 6,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1450,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "nyu-langone-imaging",
    name: "NYU Langone Advanced Imaging",
    address: {
      line1: "660 First Ave",
      city: "New York",
      state: "NY",
      zip: "10016",
    },
    coords: { lat: 40.7421, lng: -73.9743 },
    phone: "(212) 555-0188",
    hours: "Mon–Fri 6am–10pm, Sat–Sun 8am–6pm",
    weeklyHours: {
      ...WEEKDAYS(6, 22),
      sat: { open: 8, close: 18 },
      sun: { open: 8, close: 18 },
    },
    modalities: [
      "MRI",
      "CT",
      "X-Ray",
      "Ultrasound",
      "Mammography",
      "PET-CT",
      "Fluoroscopy",
    ],
    subspecialties: ["Neuro", "MSK", "Body", "Cardiac", "Pediatric"],
    accreditations: [
      "ACR-MRI",
      "ACR-CT",
      "ACR-Mammography",
      "ACR-Breast-MRI",
      "ACR-Ultrasound",
      "ACR-Nuclear",
      "ACR-Stereotactic-Breast",
    ],
    patientRating: 4.8,
    reviewCount: 1890,
    avgTurnaroundHours: 24,
    nextAvailableHours: 48,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "Anthem",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1850,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: false,
  },
  {
    id: "park-ave-diagnostics",
    name: "Park Avenue Diagnostics",
    address: {
      line1: "1015 Park Ave",
      city: "New York",
      state: "NY",
      zip: "10028",
    },
    coords: { lat: 40.7793, lng: -73.9601 },
    phone: "(212) 555-0210",
    hours: "Mon–Fri 8am–7pm",
    weeklyHours: WEEKDAYS(8, 19),
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound"],
    subspecialties: ["Neuro", "MSK"],
    accreditations: ["ACR-MRI", "ACR-CT", "ACR-Ultrasound"],
    patientRating: 4.9,
    reviewCount: 287,
    avgTurnaroundHours: 12,
    nextAvailableHours: 72,
    acceptsWalkIns: false,
    inNetworkInsurance: ["Aetna", "BlueCross", "Cigna"],
    estimatedMriCostUSD: 2100,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "soho-imaging",
    name: "SoHo Imaging Center",
    address: {
      line1: "121 Spring St",
      city: "New York",
      state: "NY",
      zip: "10012",
    },
    coords: { lat: 40.7242, lng: -73.9989 },
    phone: "(212) 555-0312",
    hours: "Mon–Sat 8am–8pm",
    weeklyHours: { ...WEEKDAYS(8, 20), sat: { open: 8, close: 20 } },
    modalities: ["MRI", "X-Ray", "Ultrasound"],
    subspecialties: ["MSK", "Body"],
    accreditations: ["ACR-MRI", "ACR-Ultrasound"],
    patientRating: 4.5,
    reviewCount: 198,
    avgTurnaroundHours: 24,
    nextAvailableHours: 12,
    acceptsWalkIns: true,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1280,
    hasOnsiteRadiologist: false,
    isExpertRadiologyPartner: true,
  },
  {
    id: "harlem-diagnostic",
    name: "Harlem Diagnostic Center",
    address: {
      line1: "215 W 125th St",
      city: "New York",
      state: "NY",
      zip: "10027",
    },
    coords: { lat: 40.808, lng: -73.9499 },
    phone: "(212) 555-0421",
    hours: "Mon–Fri 7am–7pm, Sat 9am–3pm",
    weeklyHours: { ...WEEKDAYS(7, 19), sat: { open: 9, close: 15 } },
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography"],
    subspecialties: ["Body", "MSK"],
    accreditations: ["ACR-MRI", "ACR-CT", "ACR-Mammography"],
    patientRating: 4.2,
    reviewCount: 156,
    avgTurnaroundHours: 36,
    nextAvailableHours: 4,
    acceptsWalkIns: true,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Medicaid",
      "Medicare",
      "UnitedHealth",
    ],
    estimatedMriCostUSD: 850,
    hasOnsiteRadiologist: false,
    isExpertRadiologyPartner: true,
  },
  {
    id: "brooklyn-heights-imaging",
    name: "Brooklyn Heights Imaging",
    address: {
      line1: "180 Montague St",
      city: "Brooklyn",
      state: "NY",
      zip: "11201",
    },
    coords: { lat: 40.6951, lng: -73.9926 },
    phone: "(718) 555-0533",
    hours: "Mon–Fri 8am–8pm, Sat 9am–4pm",
    weeklyHours: { ...WEEKDAYS(8, 20), sat: { open: 9, close: 16 } },
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography"],
    subspecialties: ["MSK", "Body", "Breast"],
    accreditations: [
      "ACR-MRI",
      "ACR-CT",
      "ACR-Mammography",
      "ACR-Ultrasound",
    ],
    patientRating: 4.4,
    reviewCount: 342,
    avgTurnaroundHours: 24,
    nextAvailableHours: 24,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "Anthem",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1100,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "park-slope-open-mri",
    name: "Park Slope Open MRI",
    address: {
      line1: "456 Seventh Ave",
      city: "Brooklyn",
      state: "NY",
      zip: "11215",
    },
    coords: { lat: 40.6677, lng: -73.9805 },
    phone: "(718) 555-0644",
    hours: "Mon–Sat 8am–7pm",
    weeklyHours: { ...WEEKDAYS(8, 19), sat: { open: 8, close: 19 } },
    modalities: ["MRI", "X-Ray"],
    subspecialties: ["MSK"],
    accreditations: ["ACR-MRI"],
    patientRating: 4.3,
    reviewCount: 124,
    avgTurnaroundHours: 48,
    nextAvailableHours: 8,
    acceptsWalkIns: false,
    inNetworkInsurance: ["Aetna", "BlueCross", "UnitedHealth", "Medicare"],
    estimatedMriCostUSD: 950,
    hasOnsiteRadiologist: false,
    isExpertRadiologyPartner: false,
  },
  {
    id: "queens-radiology",
    name: "Queens Radiology Associates",
    address: {
      line1: "31-15 Steinway St",
      city: "Astoria",
      state: "NY",
      zip: "11103",
    },
    coords: { lat: 40.762, lng: -73.9159 },
    phone: "(718) 555-0755",
    hours: "Mon–Fri 7am–9pm, Sat 8am–5pm",
    weeklyHours: { ...WEEKDAYS(7, 21), sat: { open: 8, close: 17 } },
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography", "DEXA"],
    subspecialties: ["Body", "MSK", "Breast"],
    accreditations: [
      "ACR-MRI",
      "ACR-CT",
      "ACR-Mammography",
      "ACR-Stereotactic-Breast",
    ],
    patientRating: 4.1,
    reviewCount: 267,
    avgTurnaroundHours: 30,
    nextAvailableHours: 12,
    acceptsWalkIns: true,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "Medicaid",
      "Medicare",
      "UnitedHealth",
    ],
    estimatedMriCostUSD: 980,
    hasOnsiteRadiologist: false,
    isExpertRadiologyPartner: true,
  },
  {
    id: "bronx-community",
    name: "Bronx Community Imaging",
    address: {
      line1: "2425 Grand Concourse",
      city: "Bronx",
      state: "NY",
      zip: "10468",
    },
    coords: { lat: 40.864, lng: -73.8985 },
    phone: "(718) 555-0866",
    hours: "Mon–Sat 7am–6pm",
    weeklyHours: { ...WEEKDAYS(7, 18), sat: { open: 7, close: 18 } },
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound"],
    subspecialties: ["Body"],
    accreditations: [],
    patientRating: 3.9,
    reviewCount: 89,
    avgTurnaroundHours: 48,
    nextAvailableHours: 2,
    acceptsWalkIns: true,
    inNetworkInsurance: ["BlueCross", "Medicaid", "Medicare"],
    estimatedMriCostUSD: 720,
    hasOnsiteRadiologist: false,
    isExpertRadiologyPartner: false,
  },
  {
    id: "hoboken-imaging",
    name: "Hoboken Imaging & MRI",
    address: {
      line1: "1 Hudson Pl",
      city: "Hoboken",
      state: "NJ",
      zip: "07030",
    },
    coords: { lat: 40.7361, lng: -74.0291 },
    phone: "(201) 555-0977",
    hours: "Mon–Fri 7am–9pm, Sat 8am–4pm",
    weeklyHours: { ...WEEKDAYS(7, 21), sat: { open: 8, close: 16 } },
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography"],
    subspecialties: ["MSK", "Neuro", "Body"],
    accreditations: [
      "ACR-MRI",
      "ACR-CT",
      "ACR-Mammography",
      "ACR-Ultrasound",
    ],
    patientRating: 4.6,
    reviewCount: 234,
    avgTurnaroundHours: 16,
    nextAvailableHours: 18,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1180,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "westchester-medical",
    name: "Westchester Medical Imaging",
    address: {
      line1: "100 Woods Rd",
      city: "Valhalla",
      state: "NY",
      zip: "10595",
    },
    coords: { lat: 41.0773, lng: -73.7831 },
    phone: "(914) 555-1088",
    hours: "Mon–Fri 6am–10pm",
    weeklyHours: WEEKDAYS(6, 22),
    modalities: [
      "MRI",
      "CT",
      "X-Ray",
      "Ultrasound",
      "Mammography",
      "PET-CT",
      "Fluoroscopy",
      "DEXA",
    ],
    subspecialties: ["Neuro", "MSK", "Body", "Cardiac", "Breast"],
    accreditations: [
      "ACR-MRI",
      "ACR-CT",
      "ACR-Mammography",
      "ACR-Breast-MRI",
      "ACR-Ultrasound",
      "ACR-Nuclear",
    ],
    patientRating: 4.6,
    reviewCount: 678,
    avgTurnaroundHours: 20,
    nextAvailableHours: 36,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "Anthem",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1350,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "long-island-rad",
    name: "Long Island Radiology Partners",
    address: {
      line1: "901 Stewart Ave",
      city: "Garden City",
      state: "NY",
      zip: "11530",
    },
    coords: { lat: 40.7268, lng: -73.6343 },
    phone: "(516) 555-1199",
    hours: "Mon–Fri 7am–8pm, Sat 8am–4pm",
    weeklyHours: { ...WEEKDAYS(7, 20), sat: { open: 8, close: 16 } },
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography", "DEXA"],
    subspecialties: ["MSK", "Body", "Breast", "Pediatric"],
    accreditations: [
      "ACR-MRI",
      "ACR-CT",
      "ACR-Mammography",
      "ACR-Ultrasound",
    ],
    patientRating: 4.4,
    reviewCount: 445,
    avgTurnaroundHours: 22,
    nextAvailableHours: 24,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "Humana",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1050,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: false,
  },
  // ── Houston metro ──
  {
    id: "houston-methodist-imaging",
    name: "Houston Methodist Diagnostic Imaging",
    address: {
      line1: "6565 Fannin St",
      city: "Houston",
      state: "TX",
      zip: "77030",
    },
    coords: { lat: 29.7104, lng: -95.3993 },
    phone: "(713) 555-1300",
    hours: "Mon–Fri 6am–10pm, Sat–Sun 8am–6pm",
    weeklyHours: {
      ...WEEKDAYS(6, 22),
      sat: { open: 8, close: 18 },
      sun: { open: 8, close: 18 },
    },
    modalities: [
      "MRI",
      "CT",
      "X-Ray",
      "Ultrasound",
      "Mammography",
      "PET-CT",
      "Fluoroscopy",
      "DEXA",
    ],
    subspecialties: ["Neuro", "MSK", "Body", "Cardiac", "Pediatric", "Breast"],
    accreditations: [
      "ACR-MRI",
      "ACR-CT",
      "ACR-Mammography",
      "ACR-Breast-MRI",
      "ACR-Ultrasound",
      "ACR-Nuclear",
      "ACR-Stereotactic-Breast",
    ],
    patientRating: 4.7,
    reviewCount: 856,
    avgTurnaroundHours: 16,
    nextAvailableHours: 24,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "Anthem",
      "BlueCross",
      "Cigna",
      "Humana",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1650,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "memorial-hermann-tmc",
    name: "Memorial Hermann TMC Imaging",
    address: {
      line1: "6411 Fannin St",
      city: "Houston",
      state: "TX",
      zip: "77030",
    },
    coords: { lat: 29.7099, lng: -95.3984 },
    phone: "(713) 555-1411",
    hours: "Mon–Fri 7am–9pm, Sat 8am–4pm",
    weeklyHours: { ...WEEKDAYS(7, 21), sat: { open: 8, close: 16 } },
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography", "PET-CT"],
    subspecialties: ["Neuro", "MSK", "Body", "Cardiac"],
    accreditations: [
      "ACR-MRI",
      "ACR-CT",
      "ACR-Mammography",
      "ACR-Ultrasound",
      "ACR-Nuclear",
    ],
    patientRating: 4.5,
    reviewCount: 612,
    avgTurnaroundHours: 22,
    nextAvailableHours: 18,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "Humana",
      "Medicare",
      "UnitedHealth",
    ],
    estimatedMriCostUSD: 1400,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "galleria-open-mri",
    name: "Galleria Open MRI",
    address: {
      line1: "5085 Westheimer Rd",
      city: "Houston",
      state: "TX",
      zip: "77056",
    },
    coords: { lat: 29.7393, lng: -95.4677 },
    phone: "(713) 555-1522",
    hours: "Mon–Sat 8am–7pm",
    weeklyHours: { ...WEEKDAYS(8, 19), sat: { open: 8, close: 19 } },
    modalities: ["MRI", "X-Ray"],
    subspecialties: ["MSK"],
    accreditations: ["ACR-MRI"],
    patientRating: 4.3,
    reviewCount: 187,
    avgTurnaroundHours: 36,
    nextAvailableHours: 6,
    acceptsWalkIns: true,
    inNetworkInsurance: ["Aetna", "BlueCross", "Humana", "Medicare"],
    estimatedMriCostUSD: 980,
    hasOnsiteRadiologist: false,
    isExpertRadiologyPartner: false,
  },
  {
    id: "texas-imaging-west",
    name: "Texas Imaging Center West",
    address: {
      line1: "14730 Memorial Dr",
      city: "Houston",
      state: "TX",
      zip: "77079",
    },
    coords: { lat: 29.766, lng: -95.645 },
    phone: "(713) 555-1633",
    hours: "Mon–Fri 7am–8pm, Sat 8am–3pm",
    weeklyHours: { ...WEEKDAYS(7, 20), sat: { open: 8, close: 15 } },
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography", "DEXA"],
    subspecialties: ["MSK", "Body", "Breast"],
    accreditations: ["ACR-MRI", "ACR-CT", "ACR-Mammography", "ACR-Ultrasound"],
    patientRating: 4.4,
    reviewCount: 234,
    avgTurnaroundHours: 24,
    nextAvailableHours: 12,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "Humana",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1150,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  // ── Chicago metro ──
  {
    id: "northwestern-imaging",
    name: "Northwestern Memorial Imaging",
    address: {
      line1: "251 E Huron St",
      city: "Chicago",
      state: "IL",
      zip: "60611",
    },
    coords: { lat: 41.8946, lng: -87.621 },
    phone: "(312) 555-2200",
    hours: "Mon–Fri 6am–10pm, Sat 8am–4pm",
    weeklyHours: { ...WEEKDAYS(6, 22), sat: { open: 8, close: 16 } },
    modalities: [
      "MRI",
      "CT",
      "X-Ray",
      "Ultrasound",
      "Mammography",
      "PET-CT",
      "Fluoroscopy",
    ],
    subspecialties: ["Neuro", "MSK", "Body", "Cardiac", "Breast"],
    accreditations: [
      "ACR-MRI",
      "ACR-CT",
      "ACR-Mammography",
      "ACR-Breast-MRI",
      "ACR-Ultrasound",
      "ACR-Nuclear",
    ],
    patientRating: 4.8,
    reviewCount: 1240,
    avgTurnaroundHours: 18,
    nextAvailableHours: 36,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "Anthem",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1750,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: false,
  },
  {
    id: "chicago-loop-diagnostic",
    name: "Chicago Loop Diagnostic",
    address: {
      line1: "200 W Madison St",
      city: "Chicago",
      state: "IL",
      zip: "60606",
    },
    coords: { lat: 41.8819, lng: -87.6354 },
    phone: "(312) 555-2311",
    hours: "Mon–Fri 7am–8pm, Sat 9am–3pm",
    weeklyHours: { ...WEEKDAYS(7, 20), sat: { open: 9, close: 15 } },
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography"],
    subspecialties: ["MSK", "Body", "Neuro"],
    accreditations: ["ACR-MRI", "ACR-CT", "ACR-Mammography", "ACR-Ultrasound"],
    patientRating: 4.5,
    reviewCount: 412,
    avgTurnaroundHours: 20,
    nextAvailableHours: 8,
    acceptsWalkIns: true,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1250,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "lincoln-park-imaging",
    name: "Lincoln Park Imaging",
    address: {
      line1: "2515 N Clark St",
      city: "Chicago",
      state: "IL",
      zip: "60614",
    },
    coords: { lat: 41.929, lng: -87.6438 },
    phone: "(312) 555-2422",
    hours: "Mon–Fri 8am–7pm, Sat 9am–3pm",
    weeklyHours: { ...WEEKDAYS(8, 19), sat: { open: 9, close: 15 } },
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography", "DEXA"],
    subspecialties: ["MSK", "Body", "Breast"],
    accreditations: [
      "ACR-MRI",
      "ACR-CT",
      "ACR-Mammography",
      "ACR-Ultrasound",
      "ACR-Stereotactic-Breast",
    ],
    patientRating: 4.4,
    reviewCount: 285,
    avgTurnaroundHours: 22,
    nextAvailableHours: 14,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "Anthem",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1100,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "south-shore-community",
    name: "South Shore Community Imaging",
    address: {
      line1: "7531 S Stony Island Ave",
      city: "Chicago",
      state: "IL",
      zip: "60649",
    },
    coords: { lat: 41.7553, lng: -87.5868 },
    phone: "(312) 555-2533",
    hours: "Mon–Sat 7am–6pm",
    weeklyHours: { ...WEEKDAYS(7, 18), sat: { open: 7, close: 18 } },
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound"],
    subspecialties: ["Body", "MSK"],
    accreditations: ["ACR-MRI"],
    patientRating: 4.0,
    reviewCount: 98,
    avgTurnaroundHours: 48,
    nextAvailableHours: 4,
    acceptsWalkIns: true,
    inNetworkInsurance: ["BlueCross", "Medicaid", "Medicare", "UnitedHealth"],
    estimatedMriCostUSD: 780,
    hasOnsiteRadiologist: false,
    isExpertRadiologyPartner: false,
  },
];

/**
 * Mock geocoder: a small lookup of well-known zips and neighborhoods across
 * the seeded metros (NYC, Houston, Chicago). Falls back to Times Square.
 */
const LOCATION_LOOKUP: Record<string, Coords> = {
  // Manhattan
  "10001": { lat: 40.7506, lng: -73.9971 }, // Midtown / Penn Station
  "10003": { lat: 40.7321, lng: -73.9892 }, // East Village
  "10011": { lat: 40.7414, lng: -74.0008 }, // Chelsea
  "10016": { lat: 40.7456, lng: -73.9789 }, // Murray Hill
  "10021": { lat: 40.7686, lng: -73.9587 }, // Upper East Side
  "10024": { lat: 40.7869, lng: -73.9754 }, // Upper West Side
  "10027": { lat: 40.811, lng: -73.9536 }, // Harlem
  // Brooklyn
  "11201": { lat: 40.6951, lng: -73.9926 },
  "11215": { lat: 40.6677, lng: -73.9805 },
  "11211": { lat: 40.7081, lng: -73.9571 }, // Williamsburg
  // Queens / Bronx / NJ / LI
  "11103": { lat: 40.762, lng: -73.9159 },
  "10468": { lat: 40.864, lng: -73.8985 },
  "07030": { lat: 40.7361, lng: -74.0291 },
  "11530": { lat: 40.7268, lng: -73.6343 },
  // Houston
  "77002": { lat: 29.7604, lng: -95.3698 }, // Downtown
  "77024": { lat: 29.7613, lng: -95.5188 }, // Memorial
  "77030": { lat: 29.7104, lng: -95.3993 }, // Texas Medical Center
  "77056": { lat: 29.7393, lng: -95.4677 }, // Galleria
  "77079": { lat: 29.766, lng: -95.645 }, // Energy Corridor
  // Chicago
  "60601": { lat: 41.8852, lng: -87.6213 }, // Loop
  "60606": { lat: 41.8819, lng: -87.6354 },
  "60611": { lat: 41.8946, lng: -87.621 }, // Streeterville
  "60614": { lat: 41.929, lng: -87.6438 }, // Lincoln Park
  "60615": { lat: 41.802, lng: -87.6044 }, // Hyde Park
  "60649": { lat: 41.7553, lng: -87.5868 }, // South Shore
  // Common neighborhood/city names
  manhattan: { lat: 40.7831, lng: -73.9712 },
  brooklyn: { lat: 40.6782, lng: -73.9442 },
  queens: { lat: 40.7282, lng: -73.7949 },
  bronx: { lat: 40.8448, lng: -73.8648 },
  "new york": { lat: 40.7589, lng: -73.9851 },
  nyc: { lat: 40.7589, lng: -73.9851 },
  hoboken: { lat: 40.7439, lng: -74.0324 },
  harlem: { lat: 40.811, lng: -73.9536 },
  soho: { lat: 40.7233, lng: -74.0029 },
  "park slope": { lat: 40.6677, lng: -73.9805 },
  houston: { lat: 29.7604, lng: -95.3698 },
  chicago: { lat: 41.8781, lng: -87.6298 },
  "lincoln park": { lat: 41.929, lng: -87.6438 },
};

const DEFAULT_ORIGIN: Coords = { lat: 40.7589, lng: -73.9851 };

/** Mock geocoder. Returns coords for known input, or NYC center fallback. */
export function geocode(input: string): { coords: Coords; matched: boolean } {
  const cleaned = input.trim().toLowerCase();
  if (!cleaned) return { coords: DEFAULT_ORIGIN, matched: false };
  const zipMatch = cleaned.match(/\b\d{5}\b/);
  if (zipMatch && LOCATION_LOOKUP[zipMatch[0]]) {
    return { coords: LOCATION_LOOKUP[zipMatch[0]], matched: true };
  }
  if (LOCATION_LOOKUP[cleaned]) {
    return { coords: LOCATION_LOOKUP[cleaned], matched: true };
  }
  for (const [key, coords] of Object.entries(LOCATION_LOOKUP)) {
    if (cleaned.includes(key)) return { coords, matched: true };
  }
  return { coords: DEFAULT_ORIGIN, matched: false };
}
