import type { Coords, ImagingCenter } from "./types";

/**
 * 12 seeded NYC-metro imaging centers with deliberately diverse profiles
 * so ranking weight changes produce visibly different orderings.
 */
export const CENTERS: ImagingCenter[] = [
  {
    id: "midtown-imaging",
    name: "Midtown Imaging Group",
    address: {
      line1: "485 Madison Ave, 6th Fl",
      city: "New York",
      state: "NY",
      zip: "10022",
    },
    coords: { lat: 40.7589, lng: -73.9745 },
    phone: "(212) 555-0142",
    hours: "Mon–Fri 7am–9pm, Sat 8am–4pm",
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography", "DEXA"],
    subspecialties: ["Neuro", "MSK", "Body"],
    patientRating: 4.7,
    reviewCount: 412,
    avgTurnaroundHours: 18,
    nextAvailableHours: 6,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1450,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "nyu-langone-imaging",
    name: "NYU Langone Advanced Imaging",
    address: {
      line1: "660 First Ave",
      city: "New York",
      state: "NY",
      zip: "10016",
    },
    coords: { lat: 40.7421, lng: -73.9743 },
    phone: "(212) 555-0188",
    hours: "Mon–Fri 6am–10pm, Sat–Sun 8am–6pm",
    modalities: [
      "MRI",
      "CT",
      "X-Ray",
      "Ultrasound",
      "Mammography",
      "PET-CT",
      "Fluoroscopy",
    ],
    subspecialties: ["Neuro", "MSK", "Body", "Cardiac", "Pediatric"],
    patientRating: 4.8,
    reviewCount: 1890,
    avgTurnaroundHours: 24,
    nextAvailableHours: 48,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "Anthem",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1850,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: false,
  },
  {
    id: "park-ave-diagnostics",
    name: "Park Avenue Diagnostics",
    address: {
      line1: "1015 Park Ave",
      city: "New York",
      state: "NY",
      zip: "10028",
    },
    coords: { lat: 40.7793, lng: -73.9601 },
    phone: "(212) 555-0210",
    hours: "Mon–Fri 8am–7pm",
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound"],
    subspecialties: ["Neuro", "MSK"],
    patientRating: 4.9,
    reviewCount: 287,
    avgTurnaroundHours: 12,
    nextAvailableHours: 72,
    acceptsWalkIns: false,
    inNetworkInsurance: ["Aetna", "BlueCross", "Cigna"],
    estimatedMriCostUSD: 2100,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "soho-imaging",
    name: "SoHo Imaging Center",
    address: {
      line1: "121 Spring St",
      city: "New York",
      state: "NY",
      zip: "10012",
    },
    coords: { lat: 40.7242, lng: -73.9989 },
    phone: "(212) 555-0312",
    hours: "Mon–Sat 8am–8pm",
    modalities: ["MRI", "X-Ray", "Ultrasound"],
    subspecialties: ["MSK", "Body"],
    patientRating: 4.5,
    reviewCount: 198,
    avgTurnaroundHours: 24,
    nextAvailableHours: 12,
    acceptsWalkIns: true,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1280,
    hasOnsiteRadiologist: false,
    isExpertRadiologyPartner: true,
  },
  {
    id: "harlem-diagnostic",
    name: "Harlem Diagnostic Center",
    address: {
      line1: "215 W 125th St",
      city: "New York",
      state: "NY",
      zip: "10027",
    },
    coords: { lat: 40.808, lng: -73.9499 },
    phone: "(212) 555-0421",
    hours: "Mon–Fri 7am–7pm, Sat 9am–3pm",
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography"],
    subspecialties: ["Body", "MSK"],
    patientRating: 4.2,
    reviewCount: 156,
    avgTurnaroundHours: 36,
    nextAvailableHours: 4,
    acceptsWalkIns: true,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Medicaid",
      "Medicare",
      "UnitedHealth",
    ],
    estimatedMriCostUSD: 850,
    hasOnsiteRadiologist: false,
    isExpertRadiologyPartner: true,
  },
  {
    id: "brooklyn-heights-imaging",
    name: "Brooklyn Heights Imaging",
    address: {
      line1: "180 Montague St",
      city: "Brooklyn",
      state: "NY",
      zip: "11201",
    },
    coords: { lat: 40.6951, lng: -73.9926 },
    phone: "(718) 555-0533",
    hours: "Mon–Fri 8am–8pm, Sat 9am–4pm",
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography"],
    subspecialties: ["MSK", "Body", "Breast"],
    patientRating: 4.4,
    reviewCount: 342,
    avgTurnaroundHours: 24,
    nextAvailableHours: 24,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "Anthem",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1100,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "park-slope-open-mri",
    name: "Park Slope Open MRI",
    address: {
      line1: "456 Seventh Ave",
      city: "Brooklyn",
      state: "NY",
      zip: "11215",
    },
    coords: { lat: 40.6677, lng: -73.9805 },
    phone: "(718) 555-0644",
    hours: "Mon–Sat 8am–7pm",
    modalities: ["MRI", "X-Ray"],
    subspecialties: ["MSK"],
    patientRating: 4.3,
    reviewCount: 124,
    avgTurnaroundHours: 48,
    nextAvailableHours: 8,
    acceptsWalkIns: false,
    inNetworkInsurance: ["Aetna", "BlueCross", "UnitedHealth", "Medicare"],
    estimatedMriCostUSD: 950,
    hasOnsiteRadiologist: false,
    isExpertRadiologyPartner: false,
  },
  {
    id: "queens-radiology",
    name: "Queens Radiology Associates",
    address: {
      line1: "31-15 Steinway St",
      city: "Astoria",
      state: "NY",
      zip: "11103",
    },
    coords: { lat: 40.762, lng: -73.9159 },
    phone: "(718) 555-0755",
    hours: "Mon–Fri 7am–9pm, Sat 8am–5pm",
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography", "DEXA"],
    subspecialties: ["Body", "MSK", "Breast"],
    patientRating: 4.1,
    reviewCount: 267,
    avgTurnaroundHours: 30,
    nextAvailableHours: 12,
    acceptsWalkIns: true,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "Medicaid",
      "Medicare",
      "UnitedHealth",
    ],
    estimatedMriCostUSD: 980,
    hasOnsiteRadiologist: false,
    isExpertRadiologyPartner: true,
  },
  {
    id: "bronx-community",
    name: "Bronx Community Imaging",
    address: {
      line1: "2425 Grand Concourse",
      city: "Bronx",
      state: "NY",
      zip: "10468",
    },
    coords: { lat: 40.864, lng: -73.8985 },
    phone: "(718) 555-0866",
    hours: "Mon–Sat 7am–6pm",
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound"],
    subspecialties: ["Body"],
    patientRating: 3.9,
    reviewCount: 89,
    avgTurnaroundHours: 48,
    nextAvailableHours: 2,
    acceptsWalkIns: true,
    inNetworkInsurance: ["BlueCross", "Medicaid", "Medicare"],
    estimatedMriCostUSD: 720,
    hasOnsiteRadiologist: false,
    isExpertRadiologyPartner: false,
  },
  {
    id: "hoboken-imaging",
    name: "Hoboken Imaging & MRI",
    address: {
      line1: "1 Hudson Pl",
      city: "Hoboken",
      state: "NJ",
      zip: "07030",
    },
    coords: { lat: 40.7361, lng: -74.0291 },
    phone: "(201) 555-0977",
    hours: "Mon–Fri 7am–9pm, Sat 8am–4pm",
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography"],
    subspecialties: ["MSK", "Neuro", "Body"],
    patientRating: 4.6,
    reviewCount: 234,
    avgTurnaroundHours: 16,
    nextAvailableHours: 18,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1180,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "westchester-medical",
    name: "Westchester Medical Imaging",
    address: {
      line1: "100 Woods Rd",
      city: "Valhalla",
      state: "NY",
      zip: "10595",
    },
    coords: { lat: 41.0773, lng: -73.7831 },
    phone: "(914) 555-1088",
    hours: "Mon–Fri 6am–10pm",
    modalities: [
      "MRI",
      "CT",
      "X-Ray",
      "Ultrasound",
      "Mammography",
      "PET-CT",
      "Fluoroscopy",
      "DEXA",
    ],
    subspecialties: ["Neuro", "MSK", "Body", "Cardiac", "Breast"],
    patientRating: 4.6,
    reviewCount: 678,
    avgTurnaroundHours: 20,
    nextAvailableHours: 36,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "Anthem",
      "BlueCross",
      "Cigna",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1350,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: true,
  },
  {
    id: "long-island-rad",
    name: "Long Island Radiology Partners",
    address: {
      line1: "901 Stewart Ave",
      city: "Garden City",
      state: "NY",
      zip: "11530",
    },
    coords: { lat: 40.7268, lng: -73.6343 },
    phone: "(516) 555-1199",
    hours: "Mon–Fri 7am–8pm, Sat 8am–4pm",
    modalities: ["MRI", "CT", "X-Ray", "Ultrasound", "Mammography", "DEXA"],
    subspecialties: ["MSK", "Body", "Breast", "Pediatric"],
    patientRating: 4.4,
    reviewCount: 445,
    avgTurnaroundHours: 22,
    nextAvailableHours: 24,
    acceptsWalkIns: false,
    inNetworkInsurance: [
      "Aetna",
      "BlueCross",
      "Cigna",
      "Humana",
      "UnitedHealth",
      "Medicare",
    ],
    estimatedMriCostUSD: 1050,
    hasOnsiteRadiologist: true,
    isExpertRadiologyPartner: false,
  },
];

/**
 * Mock geocoder: a small lookup of well-known NYC-area zips and neighborhoods.
 * Anything else falls back to Times Square (a sensible NYC center).
 */
const LOCATION_LOOKUP: Record<string, Coords> = {
  // Manhattan
  "10001": { lat: 40.7506, lng: -73.9971 }, // Midtown / Penn Station
  "10003": { lat: 40.7321, lng: -73.9892 }, // East Village
  "10011": { lat: 40.7414, lng: -74.0008 }, // Chelsea
  "10016": { lat: 40.7456, lng: -73.9789 }, // Murray Hill
  "10021": { lat: 40.7686, lng: -73.9587 }, // Upper East Side
  "10024": { lat: 40.7869, lng: -73.9754 }, // Upper West Side
  "10027": { lat: 40.811, lng: -73.9536 }, // Harlem
  // Brooklyn
  "11201": { lat: 40.6951, lng: -73.9926 },
  "11215": { lat: 40.6677, lng: -73.9805 },
  "11211": { lat: 40.7081, lng: -73.9571 }, // Williamsburg
  // Queens / Bronx / NJ / LI
  "11103": { lat: 40.762, lng: -73.9159 },
  "10468": { lat: 40.864, lng: -73.8985 },
  "07030": { lat: 40.7361, lng: -74.0291 },
  "11530": { lat: 40.7268, lng: -73.6343 },
  // Common neighborhood names
  manhattan: { lat: 40.7831, lng: -73.9712 },
  brooklyn: { lat: 40.6782, lng: -73.9442 },
  queens: { lat: 40.7282, lng: -73.7949 },
  bronx: { lat: 40.8448, lng: -73.8648 },
  "new york": { lat: 40.7589, lng: -73.9851 },
  nyc: { lat: 40.7589, lng: -73.9851 },
  hoboken: { lat: 40.7439, lng: -74.0324 },
  harlem: { lat: 40.811, lng: -73.9536 },
  soho: { lat: 40.7233, lng: -74.0029 },
  "park slope": { lat: 40.6677, lng: -73.9805 },
};

const DEFAULT_ORIGIN: Coords = { lat: 40.7589, lng: -73.9851 };

/** Mock geocoder. Returns coords for known input, or NYC center fallback. */
export function geocode(input: string): { coords: Coords; matched: boolean } {
  const cleaned = input.trim().toLowerCase();
  if (!cleaned) return { coords: DEFAULT_ORIGIN, matched: false };
  const zipMatch = cleaned.match(/\b\d{5}\b/);
  if (zipMatch && LOCATION_LOOKUP[zipMatch[0]]) {
    return { coords: LOCATION_LOOKUP[zipMatch[0]], matched: true };
  }
  if (LOCATION_LOOKUP[cleaned]) {
    return { coords: LOCATION_LOOKUP[cleaned], matched: true };
  }
  for (const [key, coords] of Object.entries(LOCATION_LOOKUP)) {
    if (cleaned.includes(key)) return { coords, matched: true };
  }
  return { coords: DEFAULT_ORIGIN, matched: false };
}
